name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      - name: Installing dependencies
        run: npm i
        
      - name: Building React
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: h30.seohost.pl
          username: ${{ secrets.PROJECTPSYCHOLOGIA_USER }}
          password: ${{ secrets.PROJECTPSYCHOLOGIA }}
          server-dir: domains/projektpsychologia.pl/public_html/
